version: '3.3'

services:
  ruby_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - REMOTE_SERVER_IP=${REMOTE_SERVER_IP}
    ports:
      - "4567:4567"
    volumes:
      - ./logs:/app/logs
