FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y postfix && \
    apt-get clean

RUN postconf -e 'smtpd_use_tls=no' && \
    postconf -e 'myhostname=localhost' && \
    postconf -e 'mydestination=localhost' && \
    postconf -e 'inet_interfaces=all' && \
    postconf -e 'relayhost='

EXPOSE 25

CMD ["postfix", "start-fg"]
